name: Predict Games

on:
  schedule:
    - cron: "13 13 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  predict-games:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6.0.10
        with:
          version: 10
          run_install: true

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Playwright browsers
        run: pnpm exec playwright install chromium

      - name: Predict results (main account)
        env:
          NODE_ENV: production
          KICKTIPP_USERNAME: ${{ secrets.KICKTIPP_USERNAME }}
          KICKTIPP_PASSWORD: ${{ secrets.KICKTIPP_PASSWORD }}
          KICKTIPP_GROUP_ID: ${{ secrets.KICKTIPP_GROUP_ID }}
          KICKTIPP_PREDICTION_STRATEGY: one-to-win
        run: pnpm start

      - name: Predict results (bot account)
        env:
          NODE_ENV: production
          KICKTIPP_USERNAME: ${{ secrets.KICKTIPP_BOT_USERNAME }}
          KICKTIPP_PASSWORD: ${{ secrets.KICKTIPP_BOT_PASSWORD }}
          KICKTIPP_GROUP_ID: ${{ secrets.KICKTIPP_GROUP_ID }}
          KICKTIPP_PREDICTION_STRATEGY: difference-ratio
        run: pnpm start

      - name: Predict results (Bundesliga Tippspiel - bot)
        env:
          NODE_ENV: production
          KICKTIPP_USERNAME: ${{ secrets.KICKTIPP_BOT_USERNAME }}
          KICKTIPP_PASSWORD: ${{ secrets.KICKTIPP_BOT_PASSWORD }}
          KICKTIPP_GROUP_ID: bundesliga-tippspiel
          KICKTIPP_PREDICTION_STRATEGY: one-to-win
        run: pnpm start

      - name: Predict results (Bundesliga Tippspiel - bot1)
        env:
          NODE_ENV: production
          KICKTIPP_USERNAME: ${{ secrets.KICKTIPP_BOT1_USERNAME }}
          KICKTIPP_PASSWORD: ${{ secrets.KICKTIPP_BOT_PASSWORD }}
          KICKTIPP_GROUP_ID: bundesliga-tippspiel
          KICKTIPP_PREDICTION_STRATEGY: difference-ratio
        run: pnpm start

      - name: Predict results (Bundesliga Tippspiel - bot2)
        env:
          NODE_ENV: production
          KICKTIPP_USERNAME: ${{ secrets.KICKTIPP_BOT2_USERNAME }}
          KICKTIPP_PASSWORD: ${{ secrets.KICKTIPP_BOT_PASSWORD }}
          KICKTIPP_GROUP_ID: bundesliga-tippspiel
          KICKTIPP_PREDICTION_STRATEGY: coefficient
        run: pnpm start

      - name: Predict results (Bundesliga Tippspiel - bot3)
        env:
          NODE_ENV: production
          KICKTIPP_USERNAME: ${{ secrets.KICKTIPP_BOT3_USERNAME }}
          KICKTIPP_PASSWORD: ${{ secrets.KICKTIPP_BOT_PASSWORD }}
          KICKTIPP_GROUP_ID: bundesliga-tippspiel
          KICKTIPP_PREDICTION_STRATEGY: expected-points
        run: pnpm start
